### ISSUE TITLE
pushSemverTag fails

### ISSUE THREAD

**Issue by peterfigure** [JavierSegoviaCordoba/semver-gradle-plugin#19]
```
> Task :pushSemverTag FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pushSemverTag'.
> Cannot call Task.dependsOn(Object...) on task ':pushSemverTag' after task has started execution.
```

**Comment by JavierSegoviaCordoba** [comment]
Fixed with https://github.com/JavierSegoviaCordoba/semver-gradle-plugin/commit/4c93828be958223f875983802c6ae714f86f591c

`pushSemverTag` task creates and pushes the tag. It can be combined with semver Gradle properties to ensure the correct tag version is created and/or pushed.

`pushSemverTag` can use a specific remote if the Gradle property `semver.remote` is set. If it is not set, `origin` is used by the default, if it doesn't exist, the first remote by name is used. If there is no remote, the task fails.
